### ISSUE TITLE
Uncaught Error: Cannot find module "simple-statistics"     at webpackMissingModule (TerriaMap.js:88731)

### ISSUE THREAD

**Issue by jakobzhao** [TerriaJS/TerriaMap#127] opened 2016-12-13 08:50 UTC
This error happened in an Ubuntu 14.04 environment.

**Comment by kring** [comment] 2016-12-13 09:31
Sounds like it could be caused by an old version of node.js.  I believe 14.04 comes with 0.10.x, but TerriaJS requires node 5.0+ and npm 3.0+ to build (0.10.x is fine to run, once it's built).  I recommend [n](https://github.com/tj/n) for managing your node version.

**Comment by jakobzhao** [comment] 2016-12-15 02:02
Thanks Kring, 
The version of nodejs is v7.2.1, and the version of npm is 3.10.10. So, it should not be a npm version issue.

I forward the log of running "sudo gulp", hope it helps.
====================the log of running 'sudo gulp'========================

[01:59:31] Using gulpfile ~/TerriaMap/gulpfile.js
[01:59:31] Starting 'lint'...
[01:59:32] Finished 'lint' after 943 ms
[01:59:32] Starting 'render-datasource-templates'...
[01:59:32] Finished 'render-datasource-templates' after 3.54 ms
[01:59:32] Starting 'copy-terriajs-assets'...
[01:59:32] Starting 'check-terriajs-dependencies'...
[01:59:32] Finished 'check-terriajs-dependencies' after 1 ms
[01:59:32] Starting 'write-version'...
[01:59:32] Finished 'write-version' after 9.61 ms
[01:59:32] Starting 'build-app'...
Hash: 77d259d0e9147a7ba9bd
Version: webpack 1.14.0
Time: 40912ms
                                Asset     Size  Chunks             Chunk Names
3628bb25d432b2c9f23eae256eb79ce3.json  65.6 kB          [emitted]  
       cbb9fe486ac9b79cc7da.worker.js   168 kB          [emitted]  
       625567839a57d5869672.worker.js  5.27 kB          [emitted]  
       3bd6993c48211ecbd8c0.worker.js  86.7 kB          [emitted]  
2d5795098960cdf313dd4ae92036218a.json  67.4 kB          [emitted]  
ea2e3cf86ccbfd9b05b9cde7dbd52a44.json  67.3 kB          [emitted]  
3d510d30d03cf9d5e7ffd7b9c3937e72.json    66 kB          [emitted]  
c2628933a3686121808a28cc4ed8efc1.json    65 kB          [emitted]  
cd58ab10a7c600da1463f2be116cb9ce.json  64.7 kB          [emitted]  
363b177dd76c36aeee3b3fd6bd1462f0.json  65.9 kB          [emitted]  
b2d57dcf896b8a3920db6b619b0fffe8.json  65.5 kB          [emitted]  
581f1910c93dae37eb2176a3d902402a.json  65.7 kB          [emitted]  
6edb05d078b53896f322264ce227819a.json    66 kB          [emitted]  
f8064c6ae49b2db0a316810cd68a9054.json  65.6 kB          [emitted]  
e3f956b4a063bb71c1eec434df9e1c19.json  65.3 kB          [emitted]  
b779d797f43643f2f9c47843bd8cf435.json  65.5 kB          [emitted]  
03fab32f0c41feab85d13041b841417c.json  67.8 kB          [emitted]  
edb8718796e889c3f97bde2f44004bbc.json  65.3 kB          [emitted]  
dc0674ed14d4470b12330b1eac6abf7b.json  64.8 kB          [emitted]  
bfd2f4888524be41b193a3141cb4a844.json    65 kB          [emitted]  
3a9aff5435f0f40c03aef6157a3edb30.json  66.1 kB          [emitted]  
2b1a5690332ecd6f460ab35b09cfe941.json  64.9 kB          [emitted]  
9ac20655e300dbc01432966a539f10df.json    65 kB          [emitted]  
a6d1fb54cead2318e8573c0430a298bc.json  65.3 kB          [emitted]  
b98b703803507f23762805b6c5995f5b.json  27.6 kB          [emitted]  
541a21bdf0bd42030b7297230a2c3fc1.json  66.4 kB          [emitted]  
31ab38fd8a409a5f223ed2aa97e26bcc.json  65.9 kB          [emitted]  
10eb5070ec6da3dce77ac9bba37514c2.json  65.4 kB          [emitted]  
       3c1eb102a692a50bc870.worker.js   193 kB          [emitted]  
bfc02c7a602192c7123f3e6b71daa9bf.json  67.1 kB          [emitted]  
1c227b3cfcf2bdef4b4aa8d5a6965110.json  66.9 kB          [emitted]  
9ad9f606869aa9952331953522602c2b.json  66.9 kB          [emitted]  
                     cesiumWorkers.js  4.58 MB          [emitted]  
 a22e6e4f04234b080bfffee8e4993335.DAC  2.08 MB          [emitted]  
 4fff67aa927fc4ecb16298f61b0cf84a.jpg  34.1 kB          [emitted]  
 b592e228bf0641d6b4f0b79e664177ab.jpg  18.2 kB          [emitted]  
 aa1788b9411f5c1262a1e34dc560fc3f.jpg   134 kB          [emitted]  
 1e6c4242b78b7717e8ffce219d09a402.jpg   168 kB          [emitted]  
 2f4b61fff1fc654b6a75d19448eeef25.jpg   184 kB          [emitted]  
 c4725d18f3c291232a047310254e85f2.jpg   139 kB          [emitted]  
 c7fdec957e0d7d159977a6f405a40738.jpg   169 kB          [emitted]  
 e4caa789e1de589c08641109a9a59131.jpg   169 kB          [emitted]  
d6032116cad7588b171e5d825501bdde.json   529 kB          [emitted]  
 8edfbe49f85e6994ebb732a110a3c502.jpg  55.8 kB          [emitted]  
 f5ad078d6d4ff7fc08ef6a3105dc2ef9.jpg  25.5 kB          [emitted]  
 a43c19e41d9212181133dc6b0daefdc7.jpg  54.6 kB          [emitted]  
 4bc9b143747260dad71fd9951b364e3a.jpg  71.9 kB          [emitted]  
 b7da0b1fd98192044be2d9807bae528a.png  77.7 kB          [emitted]  
 3456d1802ab2ef330ae2732387726771.png    72 kB          [emitted]  
 13d842d1bd88d606d0e2a710222d48c1.png  68.3 kB          [emitted]  
 efa2f6c408eb790753a9b5fb2f3dc678.png  41.5 kB          [emitted]  
 78303112301085744794e356ff2dca25.png  72.7 kB          [emitted]  
 1bf410692dcdf215fbe68099e8cb285b.png  40.8 kB          [emitted]  
 d8b97d3e38a0d43e5a06dea9aae17a3e.png    26 kB          [emitted]  
 b7ddbf3ecb52008a53e8dc404081bd87.png  20.2 kB          [emitted]  
                         TerriaMap.js  29.9 MB       0  [emitted]  main
                        TerriaMap.css   275 kB       0  [emitted]  main
chunk    {0} TerriaMap.js, TerriaMap.css (main) 11.4 MB [rendered]

ERROR in ./~/terriajs/lib/Models/LegendHelper.js
Module not found: Error: Cannot resolve module 'simple-statistics' in /home/jakobzhao/TerriaMap/node_modules/terriajs/lib/Models
 @ ./~/terriajs/lib/Models/LegendHelper.js 16:18-46
Child worker:
                             Asset    Size  Chunks             Chunk Names
    cbb9fe486ac9b79cc7da.worker.js  168 kB       0  [emitted]  main
    chunk    {0} cbb9fe486ac9b79cc7da.worker.js (main) 57.9 kB [rendered]
Child worker:
                             Asset    Size  Chunks             Chunk Names
    3c1eb102a692a50bc870.worker.js  193 kB       0  [emitted]  main
    chunk    {0} 3c1eb102a692a50bc870.worker.js (main) 70.6 kB [rendered]
Child worker:
                             Asset     Size  Chunks             Chunk Names
    625567839a57d5869672.worker.js  5.27 kB       0  [emitted]  main
    chunk    {0} 625567839a57d5869672.worker.js (main) 512 bytes [rendered]
Child worker:
                             Asset     Size  Chunks             Chunk Names
    3bd6993c48211ecbd8c0.worker.js  86.7 kB       0  [emitted]  main
    chunk    {0} 3bd6993c48211ecbd8c0.worker.js (main) 30.5 kB [rendered]
Child worker:
                                    Asset     Size  Chunks             Chunk Names
    dc0674ed14d4470b12330b1eac6abf7b.json  64.8 kB                     
    2d5795098960cdf313dd4ae92036218a.json  67.4 kB                     
    3d510d30d03cf9d5e7ffd7b9c3937e72.json    66 kB                     
    c2628933a3686121808a28cc4ed8efc1.json    65 kB                     
    cd58ab10a7c600da1463f2be116cb9ce.json  64.7 kB                     
    363b177dd76c36aeee3b3fd6bd1462f0.json  65.9 kB                     
    b2d57dcf896b8a3920db6b619b0fffe8.json  65.5 kB                     
    581f1910c93dae37eb2176a3d902402a.json  65.7 kB                     
    6edb05d078b53896f322264ce227819a.json    66 kB                     
    f8064c6ae49b2db0a316810cd68a9054.json  65.6 kB                     
    e3f956b4a063bb71c1eec434df9e1c19.json  65.3 kB                     
    b779d797f43643f2f9c47843bd8cf435.json  65.5 kB                     
    03fab32f0c41feab85d13041b841417c.json  67.8 kB                     
    edb8718796e889c3f97bde2f44004bbc.json  65.3 kB                     
    ea2e3cf86ccbfd9b05b9cde7dbd52a44.json  67.3 kB                     
    bfd2f4888524be41b193a3141cb4a844.json    65 kB                     
    3a9aff5435f0f40c03aef6157a3edb30.json  66.1 kB                     
    2b1a5690332ecd6f460ab35b09cfe941.json  64.9 kB                     
    9ac20655e300dbc01432966a539f10df.json    65 kB                     
    a6d1fb54cead2318e8573c0430a298bc.json  65.3 kB                     
    b98b703803507f23762805b6c5995f5b.json  27.6 kB                     
    541a21bdf0bd42030b7297230a2c3fc1.json  66.4 kB                     
    31ab38fd8a409a5f223ed2aa97e26bcc.json  65.9 kB                     
    10eb5070ec6da3dce77ac9bba37514c2.json  65.4 kB                     
    3628bb25d432b2c9f23eae256eb79ce3.json  65.6 kB                     
    bfc02c7a602192c7123f3e6b71daa9bf.json  67.1 kB                     
    1c227b3cfcf2bdef4b4aa8d5a6965110.json  66.9 kB                     
    9ad9f606869aa9952331953522602c2b.json  66.9 kB                     
                         cesiumWorkers.js  4.58 MB       0  [emitted]  main
    chunk    {0} cesiumWorkers.js (main) 1.75 MB [rendered]
    
    WARNING in ./~/terriajs-cesium/Source/Workers ^\.\/.*$
    Module not found: Error: a dependency to an entry point is not allowed
     @ ./~/terriajs-cesium/Source/Workers ^\.\/.*$
    
    WARNING in ./~/terriajs-cesium/Source/Workers ^\.\/.*$
    Module not found: Error: a dependency to an entry point is not allowed
     @ ./~/terriajs-cesium/Source/Workers ^\.\/.*$
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 9.7 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 14 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.99 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 10.2 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 11.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 10.6 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 12.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 13 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 5.55 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 8.27 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 5.35 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 5.25 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 3.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 12.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 38 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 68 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 56 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 28.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 30.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 66.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 8.71 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 49.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 72.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 74 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 64.7 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 80.2 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 73.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 38.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 30.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 96.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 85.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 68.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 67.2 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 39 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 74.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 75.6 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 29.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 29.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 24.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 36.6 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 29.7 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 29.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 47.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 54.4 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 24.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 65.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 69.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 69.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 72.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 40.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 29.7 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 27.4 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 29 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 12.2 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 44.8 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 65.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 68.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 41.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 40.7 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 12.1 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 31.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 60.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 72.8 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 52 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 74 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 44.4 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 67.6 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 45.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 28.5 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 79.3 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 31.4 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 24.2 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 83.8 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 37.7 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 88.9 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 99.6 kB [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 85.4 kB [rendered]
[02:00:15] 'build-app' errored after 43 s
[02:00:15] Error in plugin 'build-specs'
Message:
    Build has errors (see above).
[02:00:16] Finished 'copy-terriajs-assets' after 44 s

**Comment by kring** [comment] 2017-01-04 05:12
Sorry for the delay on this.  `simple-statistics` is certainly in TerriaJS's package.json, so I'm not sure why it would be missing on your system.  Maybe you received errors via npm install?  I'm going to close this issue, but if you're still having trouble, please raise the question on [gitter](https://gitter.im/TerriaJS/terriajs) or the [forum](https://groups.google.com/forum/#!forum/terriajs).

**Closed by kring** 2017-01-04 05:12 UTC

**Comment by jakobzhao** [comment] 2017-01-06 04:20
Okay, I will test it again. Happy new year! I have to say TerriaJS is a great project.

Bo
