### ISSUE TITLE
Cesium OSM Buildings | TerriaMap-next

### ISSUE THREAD

**Issue by arytonsenna** [TerriaJS/TerriaMap#499] opened 2020-10-31 13:03 UTC
I am trying to load osm 3d Buildings using the following catalog item :

`{ "name": "Cesium OSM Buildings", "type": "3d-tiles", "isEnabled":"true", "isMappable":"true", "isShown":"true", "cacheDuration":"1d", "ionAssetId": 96188, "style": { "color": "Boolean(${feature['cesium#color']}) ? color(${feature['cesium#color']}) : rgb(255,255,255)" }, "colorBlendMode": "HIGHLIGHT" }`

But unfortunately when i open TerriaJsMap-next at localhost:3001 using gulp watch
i cannot load the osm buildings layer
and it says that -> "This dataset may currently be experiencing issues"
<img width="368" alt="cesium-osm-bug" src="https://user-images.githubusercontent.com/28485076/97779936-73ba2700-1ba7-11eb-956f-7c033c746da4.PNG">same is true for "cesium-terrain" layer, but i know for a fact that the layers are functional on TerriaJSMap on the previous version. What might be the issue ?

**Comment by RussellGrew** [comment] 2021-02-04 02:14
Duplicate of https://github.com/TerriaJS/terriajs/issues/4949 and can be closed

**Closed** 2021-02-05 08:04 UTC
